import os
import time
print('Please wait...')
os.system('termux-setup-storage')
time.sleep(3)
os.system('clear')
os.system('pkg  install figlet')
print('\033[0;33m')
os.system('clear')
os.system('figlet Khaled Hussein')
print()
os.system(' echo telgram: https://t.me/+DP3qE2MEFAxmODA0')
print()
os.system('echo telgram: https://t.me/+vqh3Lnq87c1lYjY8')
print()
os.system('echo telgram: https://t.me/MRTermux1')
print('\033[0;31m')
print('1) metasploit')
print('\033[1;32m')
print('2) nmap ')
print('\033[0;33m')
print('3) sublist3r')
print('\033[0;34m')
print('4) seeker')
print('\033[0;35m')
print('5) sqlmap')
print('\033[0;36m')
print('6) zphisher')
print('\033[0;37m')
print('7) hydra ')
print('\033[0;31m')
print('8) nikto')
print('\033[1;32m')
print('9) aircrack-ng')
print('\033[0;33m')
print('10) john the Ripper')
print('\033[0;34m')
print('11) cupp')
print('\033[0;36m')
print('12) hashcat')
print('\033[0;34m')
print('13) whatweb')
print('\033[1;32m')
print('14) whois')
print('\033[0;31m')
print('15) Hash-id')
print('\033[0;34m')
print('16) ALIENS.HaCK.Camera')
print('\033[0;33m')
print('17) Virus')
print('\033[0;37m')
print('18) ipdrone')
print('\033[0;36m')
print('19) recon-ng')
print('\033[0;33m')
print('20) crunch')
print('\033[0;36m')
a=input('Choose a number to install the tool :')
if a == '1':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install wget')
   os.system('wget https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/metasploit.sh')
   os.system('chmod +x metasploit.sh')
   os.system('bash metasploit.sh')
   os.system('clear')
   print('copy these commands and paste')
   print('#'*20)
   print('cd ..')
   print('cd usr')
   print('mkdir opt')
   print('cd ')
   print('mv metasploit-framework /data/data/com.termux/files/usr/opt')
   print('bash metasploit.sh')
   print('#'*20)
elif a == '2':
     os.system('pkg update && pkg upgrade')
     os.system('pkg  install nmap')
     os.system('clear')
     print('\033[1;32m')
     print('THE TOOL IS INSTALLED')
elif a =='3':
     os.system('pkg  update && pkg  upgrade')
     os.system('pkg install git ')
     os.system('pkg install python && pkg install python3')
     os.system('git clone https://github.com/aboul3la/Sublist3r.git')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('cd Sublist3r')
     print('pip install -r requirements.txt')
     print('python sublist3r.py -d <website>')
     print('#'*20)
elif a =='4':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install git')
     os.system('pkg install php')
     os.system('pkg install python3')
     os.system(' git clone https://github.com/thewhiteh4t/seeker.git')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print(' cd seeker')
     print('chmod +x *')
     print('./install.sh')
     print('python3 seeker.py')
     print('#'*20)
elif a == '5':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install proot-distro')
     os.system('proot-distro install ubuntu')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('proot-distro login ubuntu')
     print('apt update')
     print('apt install sqlmap ')
     print('sqlmap')
elif a == '6':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install git')
     os.system('pkg install php')
     os.system('git clone https://github.com/htr-tech/zphisher')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('cd zphisher')
     print('chmod +x *')
     print('./zphisher.sh')
     print('#'*20)
elif a == '7':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install proot-distro')
     os.system('proot-distro install ubuntu')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('proot-distro login ubuntu')
     print('apt update')
     print('apt install hydra')
     print('#'*20)
elif a == '8':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install proot-distro')
     os.system('proot-distro install ubuntu')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('proot-distro login ubuntu')
     print('apt update')
     print('apt install nikto')
     print('#'*20)
elif a == '9':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install proot-distro')
     os.system('proot-distro install ubuntu')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('proot-distro login ubuntu')
     print('apt update')
     print('apt install aircrack-ng')
     print('#'*20)
elif a == '10':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install proot-distro')
     os.system('proot-distro install ubuntu')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('proot-distro login ubuntu')
     print('apt update')
     print('apt install john')
     print('#'*20)
elif a == '11':
     os.system('pkg update && pkg upgrade')
     os.system('pkg install proot-distro')
     os.system('proot-distro install ubuntu')
     os.system('clear')
     print('copy these commands and paste')
     print('#'*20)
     print('proot-distro login ubuntu')
     print('apt update')
     print('apt install cupp')
     print('#'*20)
if a =='12':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install proot-distro')
   os.system('proot-distro install ubuntu')
   os.system('clear')
   print('copy these commands and paste')
   print('#'*20)
   print('proot-distro login ubuntu')
   print('apt update')
   print('apt install hashcat')
   print('#'*20)
if a == '13':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install proot-distro')
   os.system('proot-distro install ubuntu')
   os.system('clear')
   print('copy these commands and paste')
   print('#'*20)
   print('proot-distro login ubuntu')
   print('apt update')
   print('apt install whatweb')
   print('#'*20)
if a == '14':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install proot-distro')
   os.system('proot-distro install ubuntu')
   os.system('clear')
   print('copy these commands and paste')
   print('#'*20)
   print('proot-distro login ubuntu')
   print('apt update')
   print('apt install whois')  
   print('#'*20)
if a == '15':
   os.system('pkgupdate && pkgupgrade')
   os.system('pkg install git')
   os.system('pkg install python3')
   os.system(' git clone https://github.com/blackploit/hash-identifier')
   os.system('clear')
   print(' copy these commands and paste  ')
   print('#'*20)
   print('cd hash-identifier')
   print('python3 hash-id.py')
   print('#'*20)
if a == '16':
   os.system('pkgupdate && pkg upgrade')
   os.system('pkg install git')
   os.system('pkg install python3')
   os.system('pkg install openssh')
   os.system('pkg install php')
   os.system('git clone https://github.com/hackermohamedPro/ALIENS.HaCK.Camera')
   os.system('clear')
   print(' copy these commands and paste  ')
   print('#'*20)
   print('cd ALIENS.HaCK.Camera')
   print('bash alienshack.sh')
   print('#'*20)
if a == '17':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install git')
   os.system('pkg install python2')
   os.system('git clone https://github.com/Amerlaceset/Amer')
   os.system('clear')
   print('copy these commands and paste')
   print('#'*20)
   print('cd Amer ')
   print('choose number 1 ')
   print('cd Virus4')
   print('python2 Virus4.py')
   print('choose number4')
   orint('#'*20)
if a == '18':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install git ')
   os.system('pkg install python3')
   os.system('git clone https://github.com/noob-hackers/ipdrone')
   os.system('clear')
   print(' copy these commands and paste  ')
   print('#'*20)
   print('cd ipdrone')
   print('python3 ipdrone.py -v <ip>')
   print('#'*20)
if a == '19':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install proot-distro')
   os.system('proot-distro install ubuntu')
   os.system('clear')
   print('copy these commands and paste')
   print('#'*20)
   print('proot-distro login ubuntu')
   print('apt update')
   print('apt install recon-ng')
   print('recon-ng')
   print('#'*20)
if a == '20':
   os.system('pkg update && pkg upgrade')
   os.system('pkg install crunch')
   os.system('clear')
   print('\033[0;36m')
   print('THE TOOL IS INSTALLED')
